version: "3"

services: 
  registry:
    image: registry:2
    container_name: registry
    restart: always
    env_file: 
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./config.yml:/etc/docker/registry/config.yml
      - /root/data:/var/lib/registry