version: 0.1
log:
  fields:
    service: registry
  level: warn
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    accesskey: replace_with_your_access_key
    secretkey: replace_with_your_secret_key
    region: replace_with_your_region
    regionendpoint: replace_with_your_region_endpoint
    bucket: replace_with_your_bucket

http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]

health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3

maintenance:
  readonly:
      enabled: true

proxy:
  remoteurl: https://registry-1.docker.io
  ttl: 168h